version: '3.3'
services:
    timeline-app:
        image: xmonline/xm-ms-timeline:${IMAGE_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/timeline-app.env
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: timeline
                syslog-facility: local7

networks:
    xm2:
        driver: overlay
